# Generated by Django 4.1.9 on 2023-05-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueName', models.CharField(max_length=15)),
                ('disasterDate', models.DateField()),
                ('province', models.CharField(max_length=15)),
                ('District', models.CharField(max_length=15)),
                ('affectedArea', models.CharField(max_length=15)),
                ('issueDescription', models.CharField(max_length=500)),
                ('expectedSolution', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTitle', models.CharField(max_length=255)),
                ('helddate', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('contributors', models.JSONField()),
                ('tasks', models.JSONField()),
            ],
        ),
    ]
