# Generated by Django 4.1.9 on 2023-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0002_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintTitle', models.CharField(max_length=200)),
                ('fileDate', models.DateField()),
                ('complaintType', models.CharField(max_length=15)),
                ('authority', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=15)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.CharField(max_length=1500),
        ),
    ]
