# Generated by Django 4.1.9 on 2023-08-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0005_floodimpact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(max_length=10)),
                ('moment', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=100)),
            ],
        ),
    ]
