# Generated by Django 4.1.9 on 2023-08-28 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planetpulseapp', '0008_alter_userdetails_telephonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('telephoneNumber', models.BigIntegerField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdetailssetup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
