# Generated by Django 4.1.9 on 2023-08-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0011_remove_webnotification_user_webnotification_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webappnotifications', to='planetpulseapp.userdetailssetup')),
            ],
        ),
        migrations.DeleteModel(
            name='WebNotification',
        ),
    ]
