# Generated by Django 4.1.9 on 2023-08-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0012_webappnotification_delete_webnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webappnotification',
            name='owner',
            field=models.BigIntegerField(),
        ),
    ]
