# Generated by Django 4.1.9 on 2023-08-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0014_disasternotification_delete_webappnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('disasterType', models.CharField(max_length=30)),
            ],
        ),
    ]
