# Generated by Django 4.1.9 on 2023-08-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0015_emergencyaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('flood', models.BooleanField()),
                ('landslide', models.BooleanField()),
                ('strongwind', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='EmergencyAction',
        ),
    ]
