# Generated by Django 4.1.9 on 2023-08-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0016_emergency_delete_emergencyaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRelief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('flood', models.BooleanField()),
                ('landslide', models.BooleanField()),
                ('strongwind', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Emergency',
        ),
    ]
