# Generated by Django 4.1.9 on 2023-08-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0017_emergencyrelief_delete_emergency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidance',
            old_name='risk',
            new_name='disaster',
        ),
        migrations.AlterField(
            model_name='guidance',
            name='action',
            field=models.CharField(max_length=1000),
        ),
    ]
