# Generated by Django 4.1.9 on 2023-08-30 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planetpulseapp', '0018_rename_risk_guidance_disaster_alter_guidance_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affectedArea', models.CharField(max_length=30)),
                ('message', models.CharField(default='Emergency alert', max_length=50)),
                ('userphone', models.BigIntegerField()),
                ('is_seen', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authoritycontact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
