# Generated by Django 4.1.9 on 2023-08-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0019_authoritycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoritycontact',
            name='respondingMessage',
            field=models.CharField(default='Notification: Rescue Operation LaunchedWe want to inform you that a rescue operation is now underway, and our team is en route to your location. Rest assured, we are working swiftly to reach you as soon as possible.', max_length=200),
        ),
    ]
