# Generated by Django 4.1.9 on 2023-08-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0020_authoritycontact_respondingmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoritycontact',
            name='owner',
        ),
    ]
