# Generated by Django 4.1.9 on 2023-09-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0021_remove_authoritycontact_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landslide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=1)),
                ('temp_min', models.DecimalField(decimal_places=1, max_digits=4)),
                ('temp_max', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rainSUm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strongwind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=1)),
                ('wind_speed', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temp_min', models.DecimalField(decimal_places=1, max_digits=4)),
                ('temp_max', models.DecimalField(decimal_places=1, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thunder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=1)),
                ('temp_min', models.DecimalField(decimal_places=1, max_digits=4)),
                ('temp_max', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rainSUm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
