# Generated by Django 4.1.9 on 2023-09-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0021_remove_authoritycontact_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('username', models.CharField(max_length=100)),
                ('automobile_emission', models.DecimalField(decimal_places=4, max_digits=10)),
                ('railway_emission', models.DecimalField(decimal_places=4, max_digits=10)),
                ('aviation', models.DecimalField(decimal_places=4, max_digits=10)),
                ('aquatic_emission', models.DecimalField(decimal_places=4, max_digits=10)),
                ('electricity_emission', models.DecimalField(decimal_places=4, max_digits=10)),
                ('waterandgas_emission', models.DecimalField(decimal_places=4, max_digits=10)),
                ('food_emission', models.DecimalField(decimal_places=4, max_digits=10)),
                ('beverages_emission', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_emission', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
