# Generated by Django 4.1.9 on 2023-09-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0022_landslide_strongwind_thunder'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandslideImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideprediction', models.CharField(max_length=1)),
                ('temp_max', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temp_min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rainSum', models.DecimalField(decimal_places=1, max_digits=4)),
                ('damaged_houses', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrongwindImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windprediction', models.CharField(max_length=1)),
                ('temp_max', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temp_min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('wind_speed', models.DecimalField(decimal_places=1, max_digits=4)),
                ('damaged_houses', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThunderImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thunderprediction', models.CharField(max_length=1)),
                ('temp_max', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temp_min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rainSum', models.DecimalField(decimal_places=1, max_digits=4)),
                ('victims', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
