# Generated by Django 4.1.9 on 2023-09-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0022_emissiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissiondata',
            name='aquatic_emission',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emissiondata',
            name='automobile_emission',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emissiondata',
            name='aviation',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emissiondata',
            name='beverages_emission',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emissiondata',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emissiondata',
            name='electricity_emission',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emissiondata',
            name='food_emission',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emissiondata',
            name='railway_emission',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emissiondata',
            name='total_emission',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emissiondata',
            name='waterandgas_emission',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
