# Generated by Django 4.1.9 on 2023-09-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0023_alter_emissiondata_aquatic_emission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100)),
                ('food_emission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('beverages_emission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100)),
                ('electricity_emission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('waterandgas_emission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionTransportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100)),
                ('automobile_emission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('railway_emission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('aviation', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('aquatic_emission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='EmissionData',
        ),
    ]
