# Generated by Django 4.1.9 on 2023-09-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0023_landslideimpact_strongwindimpact_thunderimpact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strongwindimpact',
            name='damaged_houses',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='thunderimpact',
            name='victims',
            field=models.CharField(max_length=100),
        ),
    ]
