# Generated by Django 4.1.9 on 2023-09-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0024_alter_strongwindimpact_damaged_houses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strongwind',
            old_name='temp_max',
            new_name='temp_avg',
        ),
        migrations.RenameField(
            model_name='strongwindimpact',
            old_name='temp_max',
            new_name='temp_avg',
        ),
        migrations.RemoveField(
            model_name='strongwind',
            name='temp_min',
        ),
        migrations.RemoveField(
            model_name='strongwindimpact',
            name='temp_min',
        ),
    ]
