# Generated by Django 4.1.9 on 2023-09-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0025_rename_temp_max_strongwind_temp_avg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrongwindImpactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windprediction', models.CharField(max_length=1)),
                ('wind_speed', models.DecimalField(decimal_places=1, max_digits=4)),
                ('temp_max', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temp_min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('damaged_houses', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrongWindInstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=1)),
                ('temp_max', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wind_speed', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temp_min', models.DecimalField(decimal_places=1, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Strongwind',
        ),
        migrations.DeleteModel(
            name='StrongwindImpact',
        ),
    ]
