# Generated by Django 4.1.9 on 2023-10-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0023_post'),
        ('planetpulseapp', '0024_emissiondiet_emissionenergy_emissiontransportation_and_more'),
        ('planetpulseapp', '0026_strongwindimpactmodel_strongwindinstances_and_more'),
    ]

    operations = [
    ]
