# Generated by Django 4.1.9 on 2023-10-28 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planetpulseapp', '0028_location_delete_emissiondiet_delete_emissionenergy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionTransportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('automobile_emission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('railway_emission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('aviation', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('aquatic_emission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('electricity_emission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('waterandgas_emission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('food_emission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('beverages_emission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
