# Generated by Django 4.1.9 on 2023-10-30 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planetpulseapp', '0030_issues_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_vehicle_emmision', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('people_count', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('bulb_type', models.CharField(max_length=255)),
                ('bulb_count', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('ac_btu', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('ac_count', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('ac_type', models.CharField(max_length=255)),
                ('refrigerator_power', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('gas_duration', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
