# Generated by Django 4.1.9 on 2023-10-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetpulseapp', '0031_emissionsetup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissionsetup',
            old_name='personal_vehicle_emmision',
            new_name='veh_emi',
        ),
    ]
