# Generated by Django 4.1.9 on 2024-04-03 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planetwatchapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogs",
            name="user",
        ),
        migrations.RemoveField(
            model_name="issues",
            name="user",
        ),
        migrations.DeleteModel(
            name="Landslide",
        ),
        migrations.DeleteModel(
            name="LandslideImpact",
        ),
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
        migrations.DeleteModel(
            name="StrongwindImpactModel",
        ),
        migrations.DeleteModel(
            name="StrongWindInstances",
        ),
        migrations.DeleteModel(
            name="Blogs",
        ),
        migrations.DeleteModel(
            name="Issues",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
